name: Rusted -test cleanup

on:
  workflow_run:
    workflows:
      - Rusted -test build
    types:
      - completed

permissions:
  actions: write

jobs:
  cleanup:
    if: contains(format(' {0} ', github.event.workflow_run.head_commit.message), ' -test ')
    runs-on: ubuntu-latest

    steps:
      - name: Wait 60 seconds
        run: sleep 60

      - name: Delete diagnostic run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.event.workflow_run.id }}
          REPOSITORY: ${{ github.repository }}
        run: |
          gh api \
            --method DELETE \
            "repos/${REPOSITORY}/actions/runs/${RUN_ID}"